apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-app-argocd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastapi-app
  template:
    metadata:
      labels:
        app: fastapi-app
    spec:
      containers:
      - name: fastapi-app
        image: underdog22a/devops-playground:latest_1
        ports:
        - containerPort: 8000
